# Generated by Django 4.2.3 on 2023-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_image',
            field=models.ImageField(default=None, upload_to='todo_images/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
